function run_all_tests()
% RUN_ALL_TESTS  Execute the complete V0/V1/V2a/V2b test suite.
%
%   Calls every test function. Prints summary. Throws error if any fail.

    fprintf('\n--- V0/V1/V2a/V2b Test Suite ---\n\n');

    tests = {@test_v0_single_link, ...
             @test_v1_two_way, ...
             @test_fractional_delay, ...
             @test_sign_convention, ...
             @test_waveform_closedform, ...
             @test_cfo_basic, ...
             @test_cfo_twtt, ...
             @test_cal_tone, ...
             @test_updown, ...
             @test_cfo_phased_oracle, ...
             @test_cfo_bias_regression, ...
             @test_updown_full, ...
             @test_coding_basic, ...
             @test_code_misalignment, ...
             @test_coding_twtt, ...
             @test_align_code_fractional, ...
             @test_code_length_study};

    names = {'test_v0_single_link (T01-T05)', ...
             'test_v1_two_way (T06-T09)', ...
             'test_fractional_delay (T10)', ...
             'test_sign_convention (T11-T12)', ...
             'test_waveform_closedform (T13)', ...
             'test_cfo_basic (C01-C06,C10,C17,C18)', ...
             'test_cfo_twtt (C07-C09,C16)', ...
             'test_cal_tone (C13-C15)', ...
             'test_updown (C11-C12)', ...
             'test_cfo_phased_oracle (C22-C25)', ...
             'test_cfo_bias_regression (C19,C26-C29)', ...
             'test_updown_full (C20-C21,C30)', ...
             'test_coding_basic (P01-P09,P15)', ...
             'test_code_misalignment (P11-P14)', ...
             'test_coding_twtt (P10)', ...
             'test_align_code_fractional (P16)', ...
             'test_code_length_study (code-length sweep)'};

    n_pass = 0;
    n_fail = 0;

    for i = 1:length(tests)
        try
            tests{i}();
            n_pass = n_pass + 1;
        catch e
            fprintf('  FAILED: %s\n    %s\n', names{i}, e.message);
            n_fail = n_fail + 1;
        end
    end

    fprintf('\n--- Results: %d passed, %d failed out of %d test groups ---\n', ...
            n_pass, n_fail, length(tests));

    if n_fail > 0
        error('run_all_tests:failure', '%d test group(s) failed.', n_fail);
    end
end

